### ISSUE TITLE
What's the differences from this?

### ISSUE THREAD

**Issue by equinusocio** [MicheleBertoli/react-render-with-params#1]
What's the differences from this pure js(babel) code?

```jsx
import React from 'react';

let Logo = ( {label} ) => {
  return (
    <div>
      <img src='/assets/images/logo.svg' draggable='false' />
      <span>{label}</span>
    </div>
  );
};

// Props validation
Logo.propTypes = {
  label: React.PropTypes.string
};

// Default props
Logo.defaultProps = {
  label: 'My logo',
};

export default Logo;
```

```html
<Logo label='My new logo' />
```

**Comment by LucaColonnello** [comment]
You can't do with class components

**Comment by MicheleBertoli** [comment]
Hey @equinusocio, thanks for your question.
There are many differences between stateless functional components and classes, you can find out more [here](https://facebook.github.io/react/docs/state-and-lifecycle.html).
As @LucaColonnello said, classes don't receive props, state and context as parameters of the render method and that's the reason why I created this package (inspired by [Preact](https://github.com/developit/preact)).
There have been [some discussions](https://github.com/facebook/react/issues/1387) in the React repository around this topic, if you are interested.
